# Generated by Django 4.0.6 on 2023-06-25 06:26

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import portfolio.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_value', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('investment_style', models.TextField(choices=[('0', 'LOW'), ('1', 'MED'), ('2', 'HIGH')])),
                ('currency', models.TextField(choices=[('CAD', 'Canadian Dollar'), ('USD', 'United States Dollar'), ('EUR', 'Euro'), ('GBP', 'Great British Pound'), ('SFR', 'Swiss Franc'), ('YEN', 'Japanese Yen')])),
                ('total_investment', models.FloatField()),
                ('total_shares', models.IntegerField()),
                ('share_price', models.FloatField()),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.pool')),
            ],
        ),
        migrations.CreateModel(
            name='ETF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('symbol', models.TextField(max_length=5)),
                ('investment_style', models.TextField(choices=[('0', 'LOW'), ('1', 'MED'), ('2', 'HIGH')])),
                ('last_trade', models.FloatField()),
                ('dividend_yield', models.FloatField()),
                ('absolute_change', models.FloatField()),
                ('percentage_change', models.TextField(validators=[portfolio.models.valid_pct])),
                ('currency', models.TextField(choices=[('CAD', 'Canadian Dollar'), ('USD', 'United States Dollar'), ('EUR', 'Euro'), ('GBP', 'Great British Pound'), ('SFR', 'Swiss Franc'), ('YEN', 'Japanese Yen')], default='USD')),
                ('last_updated', models.DateTimeField(default=django.utils.timezone.now)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio')),
            ],
        ),
    ]
