"""
Django settings for minvest project.

Generated by 'django-admin startproject' using Django 1.10.3.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '64fz=z=_v15$zbrd3@9f%!xbenkk^ud14onz_(rp1^hhm^i0z5'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*','192.168.56.114']

AUTH_USER_MODEL = 'accounts.CustomUser'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'accounts.apps.AccountsConfig',
    'portfolio.apps.PortfolioConfig'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'minvest.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'minvest.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django_cockroachdb',
        'NAME': 'invest',
        'USER': 'keval',
        'PASSWORD': 'sBEYQ-BVdY1X3HGhCMtj-w',
        'HOST': 'crater-gerbil-5152.8nk.cockroachlabs.cloud',
        'PORT': '26257',
        'OPTIONS': {
            'sslmode': 'verify-full'
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_URL = '/static/'

# NESSIE API KEy
NESSIE_API_KEY = '2cfd9e99a29ba1479a654765e2c2e521'
NESSIE_INVESTMENT_CUSTOMER = '582803ac360f81f10454a8ef'
NESSIE_INVESTMENT_ACCOUNT = '582803f2360f81f10454a8f1'

ETF_MASTER_LIST = [
    'AADR',
    'AAXJ',
    'ACIM',
    'ACTX',
    'ACWF',
    'ACWI',
    'ACWV',
    'ACWX',
    'ADRA',
    'ADRD',
    'ADRE',
    'ADRU',
    'ADZ',
    'AFK',
    'AFTY',
    'AGA',
    'AGF',
    'AGG',
    'AGGY',
    'AGND',
    'AGQ',
    'AGZ',
    'AGZD',
    'AIA',
    'AIRR',
    'ALD',
    'ALFA',
    'ALFI',
    'ALTS',
    'ALTY',
    'AMJ',
]

RISK_LEVELS = [
        ('0', 'LOW'),
        ('1', 'MED'),
        ('2', 'HIGH')
    ]

CURRENCIES = [
    ('CAD', 'Canadian Dollar'),
    ('USD', 'United States Dollar'),
    ('EUR', 'Euro'),
    ('GBP', 'Great British Pound'),
    ('SFR', 'Swiss Franc'),
    ('YEN', 'Japanese Yen')
]